---
#
# Ansible managed
#
repository:
  description: Prepare your system to be managed by Ansible.
  homepage: https://buluma.github.io/
  topics: bootstrap, python, sudo, system, ansible, molecule, tox, playbook
