---
- name: Converge
  hosts: all
  # This role installs packages using the `raw` module and needs to connect as
  # `root`. (`sudo` is not available before bootstrapping.) All tasks in the
  # role have `become` set to `false`, so you can use either `false` or `true`
  # for `become`, the role will not use become (so `sudo`) for any task.
  become: true # `false` will also work.
  # This role installs python, gathering facts can't be done before `python` is
  # installed. This role runs the `setup` module, so facts will be available
  # after running the role.
  gather_facts: false

  pre_tasks:
    - name: Install python3 and sudo
      ansible.builtin.raw: |
        if command -v dnf 2>/dev/null; then
          dnf install -y python3 sudo
        elif command -v apt-get 2>/dev/null; then
          apt-get install -y python3 sudo
        elif command -v apk 2>/dev/null; then
          apk add python3 sudo
        fi
      become: false
      changed_when: true

    - name: Find EXTERNALLY-MANAGED files
      ansible.builtin.find:
        paths: /usr/lib
        patterns: "EXTERNALLY-MANAGED"
        recurse: true
      register: externally_managed_files

    - name: Remove EXTERNALLY-MANAGED files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ externally_managed_files.files }}"

  roles:
    - role: buluma.bootstrap
