---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if sudo works
      ansible.builtin.command:
        cmd: sudo -V
      register: sudo_version
      changed_when: false

    - name: Show sudo version
      ansible.builtin.debug:
        var: sudo_version.stdout

    - name: Check if python is installed
      ansible.builtin.command:
        cmd: python3 --version
      register: python_version
      changed_when: false

    - name: Show python version
      ansible.builtin.debug:
        var: python_version.stdout

    - name: Check sudo configuration
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "id"
        - "whoami"
        - "sudo -V"
      register: sudo_check
      changed_when: false
      ignore_errors: true
      when: ansible_facts['distribution'] == "Fedora"

    - name: Show sudo configuration
      ansible.builtin.debug:
        var: sudo_check
      when: ansible_facts['distribution'] == "Fedora"
