---
#
# Ansible managed
#

name: Auto Merge Dependency Updates

on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Dependabot Updates
        uses: buluma/gh-action-auto-merge-dependabot-updates@1.0.3
        with:
          allowed-actors: dependabot-preview[bot], dependabot[bot]
